POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "hans-wurst",
    "number": "4698464654"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "4698464654"
}